{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "haproxytech-ingress.name" . }}
    chart: {{ template "haproxytech-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "haproxytech-ingress.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "haproxytech-ingress.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "haproxytech-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
