{{ if eq .Values.controller.kind "Deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "haproxytech-ingress.name" . }}
    chart: {{ template "haproxytech-ingress.chart" . }}
    release: {{ .Release.Name }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
  name: {{ template "haproxytech-ingress.fullname" . }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "haproxytech-ingress.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "haproxytech-ingress.name" . }}
        component: "{{ .Values.controller.name }}"
        release: {{ .Release.Name }}
        {{- if .Values.controller.podLabels }}
{{ toYaml .Values.controller.podLabels | indent 8 }}
        {{- end }}
    spec:
      {{ template "haproxytech-ingress.podSpec" . }}
{{- end }}
